### ISSUE TITLE
What is the stats.json?

### ISSUE THREAD

**Issue by Valeriy1991** [damienbod/Angular2WebpackVisualStudio#12]
Hi!

What is the "stats.json" file and how can I generate it?

**Comment by robisim74** [comment]
Hi,

this file contains the statistics of webpack bundle file. You can generate it from the command line:

`webpack --profile --json > stats.json`

or via a plugin for webpack.

Greetings

**Comment by Valeriy1991** [comment]
Thanks! This issue is closed.
