### ISSUE TITLE
1.0.0-preview2-003121

### ISSUE THREAD

**Issue by MaherJendoubi** [damienbod/Angular2WebpackVisualStudio#14]
![image](https://cloud.githubusercontent.com/assets/1798510/19415921/4fe462ae-9380-11e6-9ef5-c9fbb39648bc.png)

**Comment by damienbod** [comment]
thanks, I'll update

**Comment by damienbod** [comment]
updated

**Comment by MaherJendoubi** [comment]
👍 👍 👍
