### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by MaherJendoubi** [damienbod/Angular2WebpackVisualStudio#15]
![image](https://cloud.githubusercontent.com/assets/1798510/19417132/104abf60-93a5-11e6-92a7-095a1a2af753.png)

**Comment by damienbod** [comment]
What do you see in F12 in the browser?

1) try a npm install from the command line
2) Do a Webpack development build

Should work. 

If not post the console messages,

Greetings Damien

**Comment by MaherJendoubi** [comment]
I get nothing in the console when I did F12...
Actually I forget to install webpack task runner...
Thanks Damien

![image](https://cloud.githubusercontent.com/assets/1798510/19417668/0de780e2-93b3-11e6-8b45-3d5408218415.png)

**Comment by damienbod** [comment]
cool, have fun

**Comment by MaherJendoubi** [comment]
👍 👍 👍
