### ISSUE TITLE
Do you support angular universal ?

### ISSUE THREAD

**Issue by JanickRoss** [damienbod/Angular2WebpackVisualStudio#16]
This seed support server-side rendering or do you have plan for that ?

**Comment by damienbod** [comment]
No not yet, sounds interesting.

Greetings Damien

**Comment by JanickRoss** [comment]
let me know if you add this support please.


thanks



Télécharger Outlook for Android






On Mon, Oct 24, 2016 at 1:33 PM -0400, "damienbod" <notifications@github.com> wrote:





No not yet, sounds interesting.

Greetings Damien

**Comment by damienbod** [comment]
angular 4 will be supporting something like this
