### ISSUE TITLE
Extend with lazy loading and basic routing features 

### ISSUE THREAD

**Issue by damienbod** [damienbod/Angular2WebpackVisualStudio#20]

**Comment by robisim74** [comment]
For my [sample app](https://github.com/robisim74/angular2localization/tree/gh-pages), I have used [angular2-router-loader](https://github.com/brandonroberts/angular2-router-loader) plugin.

I have tried many solutions, but it seems the best, and it works fine with both JiT and with AoT compilation.

**Comment by damienbod** [comment]
closing, solved in Roberto's links, thanks
