### ISSUE TITLE
Need to improve the dev debug experience for the dev build

### ISSUE THREAD

**Issue by damienbod** [damienbod/Angular2WebpackVisualStudio#23]
@robisim74 @FabianGosebrink all

Hi I've encountered various small issues with the dev build, and I would like to improve the dev build, debug developer experience. 
 
have small issues with:
- bundle cache for dev build
- dev bundle size (DUE to webpack -d !!!! configured for eval-cheap-module-source-map)
- map files not linked in the dev build (incorrect, this is fine!)
- breakpoint debugging in VS not working (debug in browser now)

The production works great which is the most important thing.

What do ye think? Would be great if we could improve this.

Greetings Damien

**Comment by robisim74** [comment]
Hi Damien,

about your questions:

- I don't understand what you mean
- dev bundle size is big because in dev mode you don't use AoT compilation, Tree shaking and minification: it's normal
- the problem is caused by this commit (https://github.com/damienbod/Angular2WebpackVisualStudio/commit/8482470af767ff505e5dc367eb51bcc0ce90ae32), which blocked the compilation of TypeScript: if you enable it, sourcemap file is generated:

![image](https://cloud.githubusercontent.com/assets/14012361/20407827/3df4f278-ad13-11e6-846d-f55158d73864.png)
I don't know a workaround for this: I think we have to enable it, because I don't see any problem.
- What debugging you mean? Client-side is normal that it doesn't work in VS, instead server-side it works:

![image](https://cloud.githubusercontent.com/assets/14012361/20407990/e1f17608-ad13-11e6-84d7-bc9c7f180b0e.png)

Greetings,

Roberto

**Comment by damienbod** [comment]
Hi Roberto

Thanks for your reply.

- sometimes when debugging, my changes where not loaded until I restarted the server. Don't know what the cause is, maybe added a hash to the dev bundle will solve this. What do you think?
- 8MB is slow to load, I thought maybe we could chuck this into smaller bits. I know it's normal, but it slow to test.
- I'll reverse this commit, this is causing the most problems The 404 caused by this slows down everything in dev.
- I use to be able to breakdown debug the ts files in VS on IE. 

I will reverse this commit and add a hash.

OK?

Greetings and thanks Damien

**Comment by damienbod** [comment]
![404bug](https://cloud.githubusercontent.com/assets/3442158/20409538/523a1e6e-ad1a-11e6-8bcd-cbc4139b0a51.png)

I have the maps back but the 404s are still there. At least the maps are back

**Comment by damienbod** [comment]
I don't have the dist/app.bundle.js.map in my dev build.

**Comment by robisim74** [comment]
Damien,

I think Visual Studio was not built (at least until now) to work client-side.

About me, I use VS only for server-side debugging and for client-side debugging I use the browser, which is normal. VS (IIS) has also some problem with the browser cache, that sometimes doesn't refresh after the changes.

404 on IE for js.map file I think is a problem of IE. Neither Edge has this problem:

![image](https://cloud.githubusercontent.com/assets/14012361/20410194/30d3b31e-ad1c-11e6-87b3-9f709ffe3376.png)

I have the dist/app.bundle.js.map in my dev build:

![image](https://cloud.githubusercontent.com/assets/14012361/20410201/40fde12e-ad1c-11e6-9981-2902d979bb59.png)

**Comment by damienbod** [comment]
strange, I deleted the node_modules, npm install, webpack dev build, add its not created. I revert the block typescript commit anyway and try tto find out why this is missing, maybe a npm package was removed

**Comment by robisim74** [comment]
Wait a moment...

**Comment by robisim74** [comment]
Don't touch the commit...

**Comment by robisim74** [comment]
Don't ask me why, but if you use webpack task runner explorer, you have only one file of 8 MB that contains also the sourcemap files... Instead, if you use npm run build from the command line, you have two files (bundle & sourcemap) of 3.5 MB

**Comment by damienbod** [comment]
me too. getting close to the src know, if I do a webpack -d from the command line, it's the same problem

**Comment by robisim74** [comment]
It's '-d' the problem!

**Comment by damienbod** [comment]
-d => --debug --devtool eval-cheap-module-source-map

**Comment by robisim74** [comment]
In any case, sourcemap files are present: but with '-d' you get one big file.

**Comment by damienbod** [comment]
yes, thanks and its only the IE which has the 404 problem. I will try to override the -d, devtool= source-map is better

**Comment by robisim74** [comment]
Great! I'm goiing to sleep now... Bye!

**Comment by damienbod** [comment]
Thanks for you help

Greetings Damien

**Comment by JoeOM** [comment]
Hi Guys 

Could you please help me. I struggle to get my breakpoints in Typescript in Visual Studio to be hit. Now I know that other people using Webpack with Visual Studio can get their Typescript breakpoints to hit. Is this an issue with your project or are there particular steps to follow to be able to debug?
