### ISSUE TITLE
Cannot find module ../aot/angular2App/app/app.module.ngfactory

### ISSUE THREAD

**Issue by Jeky11** [damienbod/Angular2WebpackVisualStudio#27]
When I run "Run - Production" task I get this error

> D:\Projects\Libs\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio> cmd /c SET NODE_ENV=production&& webpack -p --color
> @@@@@@@@@ USING PRODUCTION @@@@@@@@@@@@@@@
> clean-webpack-plugin: D:\Projects\Libs\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\wwwroot\dist has been removed.
> clean-webpack-plugin: D:\Projects\Libs\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\wwwroot\fonts has been removed.
> clean-webpack-plugin: D:\Projects\Libs\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\wwwroot\assets has been removed.
> Hash: 4f2f41544c1ee0ba4915
> Version: webpack 2.1.0-beta.27
> Time: 23676ms
>     + 556 hidden modules

> ERROR in ./angular2App/main-aot.ts
> Module not found: Error: Can't resolve '../aot/angular2App/app/app.module.ngfactory' in 'D:\Projects\Libs\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\angular2App'
>  @ ./angular2App/main-aot.ts 5:0-81
> ERROR in [default] D:\Projects\Libs\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\angular2App\main-aot.ts:7:35 
> Cannot find module '../aot/angular2App/app/app.module.ngfactory'.
> Child html-webpack-plugin for "index.html":
>         + 1 hidden modules
> Process terminated with code 2.

Can someone help me? "Run - Development" currently works but I had problems with node-sass

**Comment by damienbod** [comment]
Hi @Jeky11 

try building the production build from the command line
> npm install
>
> npm run buildProduction

If the production build is successful, a aot folder will be created. You need the latest version of node and npm.

Greetings Damien

**Comment by Jeky11** [comment]
Thank you very much. It helped. I used Webpack task runner
