### ISSUE TITLE
wwwroot/fonts

### ISSUE THREAD

**Issue by maksir** [damienbod/Angular2WebpackVisualStudio#28]
1. Why fonts folder once cleared and never be created again?

Clear:
`plugins: [
        new CleanWebpackPlugin(
            [
                './wwwroot/dist',
                './wwwroot/fonts',
`

New place - **wwwroot/assets/**:
`
{
                test: /\.(png|jpg|gif|ico|woff|woff2|ttf|svg|eot)$/,
                exclude: /node_modules/,
                loader: "file-loader?name=assets/[name]-[hash:6].[ext]",
            },
`

2. If use FontAwesome, need add to webpack.*.js  for all ext (**woff**, **woff2**, **eot**, **svg**, **ttf**)
`
{ test: /\.woff(\?v=\d+\.\d+\.\d+)?$/, exclude: /node_modules/, loader: "file?name=assets/[name]-[hash:6].[ext]" }
`

**Comment by damienbod** [comment]
@maksir I'll have a look,, could be a bug, need to check it out

Greetings Damien

**Comment by damienbod** [comment]
fixed, the fonts folder and contents are no longer removed.
