### ISSUE TITLE
Error on Production Build

### ISSUE THREAD

**Issue by nitin27may** [damienbod/Angular2WebpackVisualStudio#33]
I am getting error Error: Can't resolve '../aot/angular2App/app/app.module.ngfactory' on building it for production, please see the attached screenshot, what changes i should make to correct it.
![error](https://cloud.githubusercontent.com/assets/8065536/21074866/ba102846-bf29-11e6-9239-63b656d69bbb.jpg)

**Comment by robisim74** [comment]
From the README:

> The production build has to be run from the command line. At present ngc, the angular compiler, can only be used from the command line.

So for production you can't use the Task Runner, but from the command line you must run:
`npm run buildProduction`

Greetings

**Comment by nitin27may** [comment]
Hi @robisim74 

Thank you ,

I tried from cmd also , but getting below error, It seems that some file is missing,:
![error2](https://cloud.githubusercontent.com/assets/8065536/21075055/9f202a36-bf2e-11e6-8bf2-0aa97cf0486c.jpg)

**Comment by nitin27may** [comment]
Hi Robin
I updated npm to latest and tried to run ngc compiler getting below error,

![error4](https://cloud.githubusercontent.com/assets/8065536/21078661/6b2686a2-bf9d-11e6-89e2-38a735981edf.jpg)

No, Aot folders get created, 
Thank you.

**Comment by robisim74** [comment]
You are running another project, not this.

**Comment by nitin27may** [comment]
yes, i have replicated it and created new project on same structure using same packages and configuration, even i am getting same error on this project also.
Thank you

**Comment by damienbod** [comment]
> npm build production will work from the cammand line if it's the same. Are all you components correct? The imports, styles, no require etc inside each component. Take a look at the example components in this repo and compare with yours.

Hope this helps

Greetings Damien

**Comment by damienbod** [comment]
Not an issue with this repo, Please reopen if incorrect

Greetings Damien
