### ISSUE TITLE
error on using styleUrls in component definition

### ISSUE THREAD

**Issue by nitin27may** [damienbod/Angular2WebpackVisualStudio#34]
Hi,

When I am using style url in component definition  for styleUrls, it's build successfully but on running app getting below error.:
Uncaught Error: Expected 'styles' to be an array of strings. 
it's working fine, if i am using angular-cli for same project.

![error3](https://cloud.githubusercontent.com/assets/8065536/21078627/e18e3eb8-bf9b-11e6-8282-f205dee478d7.jpg)

when i am using inline css it's working fine, but there are some cases when the url need to mentioned in component.

**Comment by damienbod** [comment]
You need to import your styles so that AOT is supported.

**Comment by damienbod** [comment]
Not an issue with this repo, Please reopen if incorrect

Greetings Damien
