### ISSUE TITLE
module not found when using lazy loading in routing

### ISSUE THREAD

**Issue by nitin27may** [damienbod/Angular2WebpackVisualStudio#35]
Hi

I am using nested modules and for defining route i am using lazy loading in routing like 

 {
    path: '',
    loadChildren: 'app/search/search.module#SearchModule'
  }

it's working good, in case i am building same project in angular cli, where in search module i have defined another routing.

Basically, I had made a project using angular cli, not i have moved in to visual studio using webpack, and i am getting this issue.

**Comment by robisim74** [comment]
See #20

**Comment by damienbod** [comment]
Hi @nitin27may I'm closing see issue #20 as @robisim74 pointed out

Thanks Damien
