### ISSUE TITLE
Cannot set property 'name' of undefined

### ISSUE THREAD

**Issue by JeffreyChan** [damienbod/Angular2WebpackVisualStudio#38]
![image](https://cloud.githubusercontent.com/assets/5321225/21357235/7103d498-c70f-11e6-8844-6d1b0de6583c.png)

nodejs version 6.92

os: win10 pro

**Comment by damienbod** [comment]
seems to  be a bug with the latest angular 2 packages, I'm looking for a solution, if I don't find a solution, I'll revert back to the 2.2.0 version which works

**Comment by damienbod** [comment]
@JeffreyChan fixed, reverted back to angular 2.2.4, versions 2.3.0, 2.3.1 and 4.beta don't work. bug is known in 2.3.0 but wasn't fixed properly.

thanks for reporting

Greetings Damien

**Comment by JeffreyChan** [comment]
thanks a lot

**Comment by damienbod** [comment]
@JeffreyChan updated to 2.4.0 now, this version works as well.
