### ISSUE TITLE
AOT can't work out with lazy loading component

### ISSUE THREAD

**Issue by JeffreyChan** [damienbod/Angular2WebpackVisualStudio#39]
I'm using angular2-router-loader to lazy loading component
here is some code:

`const fromListRoutes: Routes = [
    {
        path: 'form-list',
        loadChildren: '../form-list/form-list.module#FormListModule'
    }
];

const appRoutes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'home', component: HomeComponent },
    { path: 'about', component: AboutComponent },
    ...fromListRoutes,
    { path: '**', redirectTo: '/home', pathMatch: 'full' },
];

export const routing = RouterModule.forRoot(appRoutes);`

then AOT operation:
`npm run ngc`

got error message: 

> Error: Cannot determine the module for class FormListComponent

**Comment by damienbod** [comment]
The  angular2-router-loader component might not be AOT conform and cannot be used in production. Need to check though. A lot of Angular 2 third party components are not suitable for production builds...

**Comment by JeffreyChan** [comment]
I see. do you have options, for lazy loading component, one of components have dynamic-reactive from.
Something like this:

> <div formArrayName="addresses">
        <div *ngFor="let address of addressesFormArray.controls; let i=index" class="panel panel-default">
            <div class="panel-heading">
                <span>Address {{i + 1}}</span>
                <span class="glyphicon glyphicon-remove pull-right" *ngIf="addressesFormArray.controls.length > 1" (click)="removeAddress(i)"></span>
            </div>
            <div class="panel-body" [formGroupName]="i">
                <address [group]="address" [addressError] = "addressErrors[i]"></address>
            </div>
        </div>
    </div>

When I run 

> npm run start

got this:
![image](https://cloud.githubusercontent.com/assets/5321225/21383809/856ef1fe-c7a2-11e6-93f8-d6847e5d2ad9.png)


I don't know it's a issue of angular2-router-loader or webpack itself?

**Comment by damienbod** [comment]
Could be a angular problem, Versions 2.3.0, 2.3.1 and 4.beta don't work!
Use Angular 2.4.0. If the  angular2-router-loader is using one of these broken versions, it won't work

Greetings Damien

**Comment by JeffreyChan** [comment]
I am using angluar2  2.4
but angluar router loader still won't work.

**Comment by damienbod** [comment]
How was  angular2-router-loader built?

**Comment by JeffreyChan** [comment]
through npm i angular2-router-loader -D
and 

>  {
                test: /\.ts$/,
                loaders: [
                    'awesome-typescript-loader',
                    'angular2-template-loader',
                    'source-map-loader',
                    'angular2-router-loader'
                ]
            }

here is my [source code](https://github.com/JeffreyChan/angluar2-best-practice).

except the dynamic reactive from, the others in sub route works fine.
so odd.

**Comment by JeffreyChan** [comment]
Hi damienbod
I think it's a issue of angular2. I just put dynamic reactive form of my code into [angular2byexample](https://github.com/chandermani/angular2byexample. )

and gulp play, still won't work.

**Comment by JeffreyChan** [comment]
hi Daminebod
I know what's wrong in my code. I forget add addresscomponet in module.
But the error messages is not very friendly.

**Comment by damienbod** [comment]
Woah, The error message gives you no indication of this.

**Comment by JeffreyChan** [comment]
hi damienbod
something like this:
![image](https://cloud.githubusercontent.com/assets/5321225/21448143/2422b880-c91a-11e6-8c7f-4837d5b2ac5f.png)
no error, just no result in console

**Comment by damienbod** [comment]
https://github.com/damienbod/Angular2WebpackVisualStudio/blob/master/LAZY_LOADING.md
