### ISSUE TITLE
Cannot read property 'harmonyModule' of null

### ISSUE THREAD

**Issue by JeffreyChan** [damienbod/Angular2WebpackVisualStudio#41]
I don't know it is a issue or not?

![image](https://cloud.githubusercontent.com/assets/5321225/21456293/00bfdace-c962-11e6-933c-080e16ce9853.png)

sometimes it will happen, usually I CTRL +C, then run npm run start. will be okay!

**Comment by damienbod** [comment]
Hi @JeffreyChan have you solved this? Can I close the issue?

Greetings Damien
