### ISSUE TITLE
ASP.Net Core 1.0.1 compatiblity

### ISSUE THREAD

**Issue by abrarjahin** [damienbod/Angular2WebpackVisualStudio#42]
ASP.Net Core 1.0.1 is released, so code should be compatible to ASP.Net Core 1.0.1

**Comment by robisim74** [comment]
@abrarjahin Currently, there are two version of .NET Core (https://www.microsoft.com/net/download/core):
 - LTS 1.0.3
 - Current 1.1

In this project we use the last one, and we can't use at the same time LTS and the Current release.

What do you mean with 1.0.1?

Greetings

**Comment by abrarjahin** [comment]
Current 1.1
