### ISSUE TITLE
The project could not be published to Azure App Service

### ISSUE THREAD

**Issue by Deilan** [damienbod/Angular2WebpackVisualStudio#43]
The errors on publish:
![error](https://cloud.githubusercontent.com/assets/4777512/21525859/fd274f5a-cd30-11e6-9aa9-e15931e6d56e.png)

**Comment by robisim74** [comment]
This isn't a publication problem, but a compilation problem (the project is compiled before the deployment). In this project TypeScript compilation is disabled, so is strange that you are getting these errors. However, before publishing, make sure you have done the following steps:
 - from the command line, build Angular app: `npm run buildProduction`
 - from Visual Studio, build solution

If you don't get errors, you can publish.

Greetings

**Comment by damienbod** [comment]
@Deilan Can I close this?
