### ISSUE TITLE
New Task Runner

### ISSUE THREAD

**Issue by robisim74** [damienbod/Angular2WebpackVisualStudio#45]
@damienbod @FabianGosebrink 

About the proposal of removing _Webpack Task Runner_: I tried to implement a new _AngularWebpack Task Runner_: it's not a problem, basically it's only necessary to change the commands and pass the commands we need.
So I thought: well, it would be enough a Task Runner that performs the npm commands, and I found that Mads has already created a Task Runner to run npm commands: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.NPMTaskRunner.

After installing it, right-clicking on the _package.json_, and all the scripts are available in VS without command line:

![image](https://cloud.githubusercontent.com/assets/14012361/21554812/11cd8a86-ce13-11e6-9c73-a0fd29365bc8.png)

I tested it, and I think it's perfect for this kind of projects: simply set the scripts that you need in _package.json_, and then the user can execute any of it.

Only recommendation for the use of this Task Runner (but really for all Task Runners) is to configure VS for the external tools: https://blogs.msdn.microsoft.com/webdev/2015/03/19/customize-external-web-tools-in-visual-studio-2015/

Greetings,

Roberto

**Comment by damienbod** [comment]
@robisim74 thanks, I don't see a point then in creating a new task runner, I will create a blog about this, when I have access to a PC again and also update the readme

**Comment by FabianGosebrink** [comment]
@robisim74 Wow, that is cool. Thank you. So we only have to mention this link (https://blogs.msdn.microsoft.com/webdev/2015/03/19/customize-external-web-tools-in-visual-studio-2015/) in the readme.md then?

BR

**Comment by robisim74** [comment]
Yes, because it's important that those who use npm commands in VS 2015 (with any Task) use the following configuration:
![image](https://cloud.githubusercontent.com/assets/14012361/21568183/a35051f6-ceb2-11e6-8607-0f6c14b20572.png)

Waiting for VS 2017...

**Comment by damienbod** [comment]
We also need a watch for dev

**Comment by robisim74** [comment]
No problem.. we can create all the scripts we need in our _package.json_
