### ISSUE TITLE
HMR not working?

### ISSUE THREAD

**Issue by Mark-Brightcloud** [damienbod/Angular2WebpackVisualStudio#47]
Could we get a guide out or a support for this feature as it's critical for development? Thanks and great job!

**Comment by FabianGosebrink** [comment]
Hey @Mark-Brightcloud,

just to be clear: Are you talking about Hot Module Replacement?

BR

**Comment by Mark-Brightcloud** [comment]
@FabianGosebrink Yes, I was talking about Hot Module Replacement. I followed previous discussion on just running "npm start", but no success. So I was hoping to get more help here. Thanks :)

**Comment by FabianGosebrink** [comment]
Have you seen [#4](https://github.com/damienbod/Angular2WebpackVisualStudio/issues/4) ?

**Comment by Mark-Brightcloud** [comment]
@FabianGosebrink Yes I have, regarding your post on "if you start the application with npm start the start-command "start": "webpack-dev-server --inline --progress --port 8080", should start a webpack-dev-server which automatically refreshes the browser. Note that it does not start the browser automatically. You have to do this manually by browsing to localhost:8080." I tried, and it didn't work. Any update?

**Comment by AlexBokhankovich** [comment]
Does anyone succeeded with HRM working via Microsoft.AspNetCore.SpaServices?
I've added the below code into startup file
```
 app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true,
                });
```
and added 
```
    "webpack-dev-middleware": "^1.9.0",
    "webpack-hot-middleware": "^2.15.0"
```
into package.json. 

When I run application in debug mode I see "[HMR] connected" message. 
When I try to change something changes are not applied automatically and even if I refresh the page.

**Comment by WhistlerHusky** [comment]
```
if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();

    try
    {
        app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
        {
            HotModuleReplacement = true,
        });
    }
    catch (Exception e)
    {
        e.Message
    }
}
```
Above code deleted the files in wwwroot 
![filesdeleted](https://cloud.githubusercontent.com/assets/10891407/22113590/c177a2f6-de34-11e6-99d2-43e08fcbc0c5.png)
then I got below error
![hmrerror](https://cloud.githubusercontent.com/assets/10891407/22113542/9b72a72c-de34-11e6-9196-c98287fdf59b.png)

Anyone solved this problem?

**Comment by damienbod** [comment]
@Mark-Brightcloud @AlexBokhankovich @WhistlerHusky @Abrissirba 
This now works, you can use the HMR using the dev build, and then the npm start.

Greetings Damien

**Comment by damienbod** [comment]
https://damienbod.com/2017/02/01/hot-module-replacement-with-angular-2-and-webpack/

**Comment by WhistlerHusky** [comment]
@damienbod 
Is it possible to use HMR without using npm start? just running f5 or ctrl +f5 to use HMR?

**Comment by frankwallis** [comment]
@WhistlerHusky you could try using https://github.com/frankwallis/WebpackAspnetMiddleware
