### ISSUE TITLE
Running from VS 2015 

### ISSUE THREAD

**Issue by tanwarsatya** [damienbod/Angular2WebpackVisualStudio#5]
This is a fantastic template working fine with Angular 2 dependencies. One issue I am facing is that this doesn't work out of the box when we try to run from VS 2015. I believe it's a small issue and I will figure out soon. Just wanted to share the same.

This work when I run via command prompt with npm start. Again very good work !!!

Satya

**Comment by damienbod** [comment]
Hi @tanwarsatya, thanks.

I'll check this, you did a clone, build VS, build webpack and run?

Greetings Damien

**Comment by tanwarsatya** [comment]
Yes a clone, build VS and run. Also tried to do webpack build and run using VS. Thx again.

**Comment by Valeriy1991** [comment]
Hi everyone!

Maybe it would be helpful.

I've got the same problem: when I've tried run the application from VS 2015 Update 3, the app does not running. Then I've tried run app through cmd and "dotnet run", and I saw an error that "Microsoft.NETCoreApp.1.0.1 was not found". After installing new version of .NET Core, the app was running successfully.

**Comment by damienbod** [comment]
I'm closing this now, re-open this if you feel that it is not closed.

Greetings Damien
