### ISSUE TITLE
Implement Lazy Loading for both dev, prod builds

### ISSUE THREAD

**Issue by damienbod** [damienbod/Angular2WebpackVisualStudio#51]
I want to implement a lazy loading example with the AboutModule as an example. Webpack should load the AboutModule separate from the main module. 

angular2-router-loader should support this.

**Comment by damienbod** [comment]
dev branch:
https://github.com/damienbod/Angular2WebpackVisualStudio/tree/lazyloading

**Comment by damienbod** [comment]
@FabianGosebrink @robisim74 Having problems getting this to work. Would be grateful for any imports

**Comment by damienbod** [comment]
Will try angular-router-loader
https://www.npmjs.com/package/angular-router-loader

**Comment by damienbod** [comment]
https://github.com/brandonroberts/angular-router-loader/blob/master/docs/options.md#loader-options-aot-compilation

**Comment by robisim74** [comment]
@damienbod Try to compare with my sample app: https://github.com/robisim74/angular2localization/tree/gh-pages (list module is lazy loaded).

You have to add the module also in tsconfig-aot, and in webpack-prod you have to change options to:
?aot=true&genDir=aot/angular2App and you have to add chunks in both webpack files.

Later I'll try the branch.

**Comment by damienbod** [comment]
thanks, I'll have a go as well

**Comment by robisim74** [comment]
@damienbod There are other changes to do: actually chunk files for lazy loaded modules are not created. If you agree, I'm going to do a commit in the new branch.

**Comment by damienbod** [comment]
@robisim74 great thanks, I won't have any time till tonight. Very grateful.

**Comment by robisim74** [comment]
Ok, I made the commit. Now a _chunk_ is created for the lazy loaded module, and it's loaded only when the user navigates to the _About_ component:

Home:
![image](https://cloud.githubusercontent.com/assets/14012361/21955287/7a7cc6f8-da68-11e6-9b70-b280397aa400.png)

About:
![image](https://cloud.githubusercontent.com/assets/14012361/21955293/afa00746-da68-11e6-973f-c65d5fcd5c83.png)

I tested with _start_, _build-dev_ and _build-production_.

If you want, It's also possible add the preloading of lazy modules: https://vsavkin.com/angular-router-preloading-modules-ba3c75e424cb#.7kx0mi63b

Greetings,

Roberto

**Comment by damienbod** [comment]
@robisim74  Amazing thanks, I was struggling with this since Friday

**Comment by FabianGosebrink** [comment]
Me too. Have to check the diff when I get back home. Thanks!!!

Sent from mobile device

________________________________

**Comment by damienbod** [comment]
@robisim74 @FabianGosebrink I'll create a blog about, merge it into the master and update the docs.

**Comment by damienbod** [comment]
https://github.com/damienbod/Angular2WebpackVisualStudio/blob/master/LAZY_LOADING.md
