### ISSUE TITLE
Npm publish angular 2 library

### ISSUE THREAD

**Issue by Antoshjkee** [damienbod/Angular2WebpackVisualStudio#52]
I have been checking different projects to create angular 2 library. 
Like this : https://github.com/preboot/angular-library-seed  and https://github.com/jvandemo/generator-angular2-library .

But problem is that I am facing some difficulties using it in Visual Studio. 

Is the any way I can use your seed project to create library? If yes, how can I achieve this? 

I am sorry if question is silly, but I am a bit stuck.

Thank you!

**Comment by damienbod** [comment]
Hi @Antoshjkee this should work without problem. The ASP.NET Core project is not required for this, you could use nodejs directly. The npm scripts run inside or outside VS. You can use the npm task  runner is you wish.

Here's a good example of an Angular 2 library.

https://github.com/robisim74/angular2localization

Greetings Damien

**Comment by Antoshjkee** [comment]
Thanks, Damien! I'am closing issue. I have created an example here [https://github.com/Antoshjkee/angular2-library-example](url)
