### ISSUE TITLE
Investigate webpack aot with ngtools

### ISSUE THREAD

**Issue by JeffreyChan** [damienbod/Angular2WebpackVisualStudio#53]
hi damien

thanks for add lazy route in your project, now I can work with my demo.

I don't change any code, just upgrade version number.

but sometimes, run ngc, will generate a lot js files, I don't like it.

do you know webpack/ngtools? it will not generate a lot js files.

here is article about [Angular2 AOT with Webpack and Lazy Loading](http://www.dzurico.com/angular-aot-webpack-lazy-loading/), would you read it?

I don't know which is better, would you give me some suggestion?

**Comment by damienbod** [comment]
thanks for the link, I'll have a look, didn't know about ngtools.
