### ISSUE TITLE
Enabling Watch - Development task runner makes vs slow

### ISSUE THREAD

**Issue by WhistlerHusky** [damienbod/Angular2WebpackVisualStudio#54]
As I enable watch - development task runner, visual studio 2015 becomes extremely slow.

Does anyone have the same problem and solve it?

**Comment by damienbod** [comment]
resharper?

**Comment by WhistlerHusky** [comment]
Yes. I'm using it. Is that because of resharper?

**Comment by damienbod** [comment]
resharper scans all the files in the project. Try deactivating resharper and see if it makes a difference.
