### ISSUE TITLE
Problem with my own app

### ISSUE THREAD

**Issue by JanneHarju** [damienbod/Angular2WebpackVisualStudio#55]
I have problem with my own app which is based on this template. My app is located in this repo https://github.com/JanneHarju/InfoScreen 
Can someone help why my app won't load any component.
I have change structure a bit. Structure follows Angular 2 tutorial https://angular.io/docs/ts/latest/tutorial/

**Comment by FabianGosebrink** [comment]
Well you have a message that says:

"Can't resolve './app.component.css'"...this should be your hint ;-)

BR

Fabian

**Comment by JanneHarju** [comment]
Sorry I missed one thing when I added my codes to repository. Can you try it now? I have still same problem. Take my latest commit.

**Comment by JanneHarju** [comment]
Now my app is working. There were many problems. I added less file conversion to web pack if you are interested in. Also I had problem with getting bootstrap styles to work.

**Comment by JanneHarju** [comment]
I must now say that I see why you did get that  can't resolve app.component.css. My git didn't recognize app.component.css file add that's why it was missed from my repository. It might something to do with when I have app.component.scss file. I renamed app.component.scc now to app2.component.css. If you are interested in about my solution you can now check it out. Its now finished. I have some future plans to it but now it works.
