### ISSUE TITLE
Child routes not getting resolved automatically

### ISSUE THREAD

**Issue by cvbc2010** [damienbod/Angular2WebpackVisualStudio#56]
I am using the solution as it is, but i added my own module into it.
Example :
1. http://localhost:5000/home resolves
2. http://localhost:5000/dashboard doesnot resolving - giving 404 for me.

it tries the two examples as 
1. home module - without Lazy Loading
2. about module - with Lazy Loading

Routes are not resolving for children automatically. can you give me a solution to go forward with this. 

These are the Routes i used :
Added DashboardModule to app Module.
**app.routes.ts :**
import { Routes, RouterModule } from '@angular/router';
import { DashboardModule } from './modules/dashboard/dashboard.module';

export const routes: Routes = [
    { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    { path: 'dashboard', loadChildren: './modules/dashboard/dashboard.module#DashboardModule' },
    { path: 'about', loadChildren: './modules/about/about.module#AboutModule' }
];
export const AppRoutes = RouterModule.forRoot(routes);

**dashboard.routes.ts:**
import { Routes, RouterModule } from '@angular/router';

import { DashboardComponent } from './components/dashboard.component';

const routes: Routes = [
    { path: '', component: DashboardComponent }
];

export const DashboardRoutes = RouterModule.forChild(routes);

**Comment by robisim74** [comment]
Did you add the new module to the _tsconfig_ files?

**Comment by cvbc2010** [comment]
yes i even tried that,i even added in tsconfig-aot too. but the same result.
But for home there is no reference for HomeModule right ?

**Comment by robisim74** [comment]
HomeModule in not lazy loaded. Did you update the router in _Startup.cs_?

**Comment by cvbc2010** [comment]
Thanks Roberto, It is solved.

And for hosting on IIS, when we create an application(Ex: TestApplication) under a DefaultWebSite(poining to localhost) .
1. In index.html src for app.bundle and polyfills.bundle are pointing to localhost ratherthan localhost/TestApplication.

Is there any approach to point them it to localhost/TestApplication. As this application is not working as an app inside a website.

output -> dist
src -> from webapplication/dist.

Thanks,
Bharani

**Comment by robisim74** [comment]
For new questions, please open new issues.

Greetings,
Roberto
