### ISSUE TITLE
Configuring dist folder as an application in IIS

### ISSUE THREAD

**Issue by cvbc2010** [damienbod/Angular2WebpackVisualStudio#57]
For hosting on IIS, when we create an application(Ex: TestApplication) under a DefaultWebSite(poining to localhost) .

In index.html 'src' for app.bundle and polyfills.bundle are pointing to localhost ratherthan localhost/TestApplication.
Is there any approach to point them it to localhost/TestApplication. As this application is not working as an app inside a website.
For example we need.
output -> dist
src -> from webapplication/dist.

Thanks,
Bharani

**Comment by cvbc2010** [comment]
I finally fixed using publicPath location to my application relative path output: of webpack.dev.config

**Comment by damienbod** [comment]
Hi @cvbc2010 
Yes you can change this innside the webpack dev and prod config files. If you search fpr dist, you will find the definitions inside the files.

Greetings Damien
