### ISSUE TITLE
Clean project not running (404)

### ISSUE THREAD

**Issue by ZOXEXIVO** [damienbod/Angular2WebpackVisualStudio#58]
Try to clone your project to new folder and try to run it. 
I see only 404 error.
Fix it, please

**Comment by FabianGosebrink** [comment]
Did you run npm install?

BR

Fabian

________________________________

**Comment by ZOXEXIVO** [comment]
of course. not only i have this issue

**Comment by damienbod** [comment]
you might need to clean up the npm packages

**Comment by ZOXEXIVO** [comment]
Hmm. I restore packages again and no result. I think, project must be run anyway at first time without any manipulations or you think another way ?

**Comment by damienbod** [comment]
Could you try this:
delete all contents inside the node_modules folder
From the commandline where the package.json is

>npm install
>npm run build-production
>dotnet run

Thanks

**Comment by andyfuniss** [comment]
I also had this problem. The above worked for me.

Thanks @damienbod
