### ISSUE TITLE
webpack plugin ahead of time compilation

### ISSUE THREAD

**Issue by damienbod** [damienbod/Angular2WebpackVisualStudio#6]
webpack plugin ahead of time compilation

**Comment by FabianGosebrink** [comment]
Have you seen there is a simple webpack plugin for this?

**Comment by damienbod** [comment]
Nop, but it sounds exactly like like what would be perfect :)

**Comment by FabianGosebrink** [comment]
https://twitter.com/juristr/status/781057969005920256

This might be exactly what we are looking for...

**Comment by damienbod** [comment]
more info:
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**Comment by damienbod** [comment]
https://github.com/blacksonic/angular2-aot-webpack
