### ISSUE TITLE
One or more projects in the solution were not loaded correctly

### ISSUE THREAD

**Issue by pappasa** [damienbod/Angular2WebpackVisualStudio#60]
One or more projects in the solution were not loaded correctly. Please see the Output Window for details.

![angular2webpackvisualstudio1](https://cloud.githubusercontent.com/assets/23055341/22500755/89915e6a-e86e-11e6-97b6-6dc106e4e7c7.jpg)
![angular2webpackvisualstudio2](https://cloud.githubusercontent.com/assets/23055341/22500843/e2d76690-e86e-11e6-82c0-dfe538f00678.jpg)

In the Output Window there is the following text:

D:\temp\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio.xproj : error : The imported project "C:\Program Files\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. D:\temp\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio.xproj

**Comment by damienbod** [comment]
Are you using  VS2017? If so try reloading the csproj. The sln file was not updated during the migration.

**Comment by damienbod** [comment]
You can also try updating to the latest .NET Core and the latest tooling

https://www.microsoft.com/net/download/core

**Comment by pappasa** [comment]
I installed DotNetCore.1.0.1-VS2015Tools.Preview2.0.3.exe, and now I get the following error message when I try to open the project:

![angular2webpackvisualstudio3](https://cloud.githubusercontent.com/assets/23055341/22507219/402a85ca-e88d-11e6-9901-86b2e0030604.jpg)

I use VS2017RC, this should have the latest .NET Core.

**Comment by damienbod** [comment]
I have ASP.NET Core 1.1 configured for this project. You seem to have 1.0.3 installed. You can either changed the global.json and the nuget packages to match your version, or upgrade to .NET 1.1. On the download page you need to click the LTS button and then download.(In the csproj file.)

PS. I have also a VS2017 branch with the conversion complete, but still version 1.1. 
Greetings Damien

**Comment by pappasa** [comment]
I installed ASP.NET Core 1.1 (dotnet-dev-win-x86.1.0.0-preview2-1-003177.exe), and now I could open the solution Angular2WebpackVisualStudio.sln, but I get the following message in the output window:

PATH=.\node_modules\.bin;C:\Program Files\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "D:\temp\Angular2WebpackVisualStudio\.vs\restore.dg"
log  : Restoring packages for D:\temp\Angular2WebpackVisualStudio\src\Angular2WebpackVisualStudio\project.json...
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.AspNetCore.StaticFiles''.
log  : Response status code does not indicate success: 407 (authenticationrequired).

![angular2webpackvisualstudio4](https://cloud.githubusercontent.com/assets/23055341/22512381/808d0e6c-e8a1-11e6-80c1-23018e6256be.jpg)

**Comment by damienbod** [comment]
node is not installed properly (per default) in VS 2017. You need to set this path inside VS 2017, and also update to the latest version node and npm with the proper version x64. This is not very nice as yet in VS 2017 but its still RC.

To check without VS 
Open in the command line at the csproj folder
$ npm install
$ npm run build-dev
$ dotnet run

All should work, then you could start fixing your VS 2017 node settings

Greetings Damien

**Comment by pappasa** [comment]
Where is the csproj folder?

**Comment by damienbod** [comment]
same place as the xproj was

https://github.com/damienbod/Angular2WebpackVisualStudio/tree/VisualStudio2017/src/Angular2WebpackVisualStudio

**Comment by pappasa** [comment]
Thank you. I downloaded https://github.com/damienbod/Angular2WebpackVisualStudio/tree/VisualStudio2017 and I opened the solution Angular2WebpackVisualStudio2017.sln, but the project is unavailable:

![angular2webpackvisualstudio5](https://cloud.githubusercontent.com/assets/23055341/22542956/fd3af448-e936-11e6-9ded-c6334c25f327.jpg)

I then tried to open src\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio.csproj and I get the following error message:

D:\temp\Angular2WebpackVisualStudio2017\src\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\temp\Angular2WebpackVisualStudio2017\src\Angular2WebpackVisualStudio\Angular2WebpackVisualStudio.csproj

![angular2webpackvisualstudio6](https://cloud.githubusercontent.com/assets/23055341/22543009/3431a276-e937-11e6-861b-b2bb5a579df5.jpg)

Could you provide a version for the latest VS2017 RC?

**Comment by damienbod** [comment]
VisualStudio/15.0.0-RC.3+26127.3

Just built and pushed a version now, which builds and runs with this version.

Greetings Damien

**Comment by damienbod** [comment]
Can I close this?
