### ISSUE TITLE
Testing framework will be integrated ?

### ISSUE THREAD

**Issue by jayapalt** [damienbod/Angular2WebpackVisualStudio#62]
Hi,

Is there any feature pull-request to incorporate / support Testing functionalities in this repo?

And Will this webpack config support Lazy-load modules with Angular App like SystemJS support?

**Comment by damienbod** [comment]
Hi @jayapalt 
testing TODO, plan to do this soon.

Webpack lazy loading works in this repo:
https://github.com/damienbod/Angular2WebpackVisualStudio/blob/master/LAZY_LOADING.md

Greetings Damien

**Comment by jayapalt** [comment]
Thanks @damienbod
