### ISSUE TITLE
Project is not running Error : This localhost page can’t be found

### ISSUE THREAD

**Issue by Prabhat2404** [damienbod/Angular2WebpackVisualStudio#63]
Hi, 

I have download given project and run but got error :
This localhost page can’t be found

No webpage was found for the web address: http://localhost:5000/
Search Google for localhost 5000
HTTP ERROR 404

![image](https://cloud.githubusercontent.com/assets/16957593/22735509/ff455ef2-ee1f-11e6-9ced-db34e94fe38b.png)

i have already install .Net core, Type script for Vs etc.... any thing i am missing ?

**Comment by damienbod** [comment]
try build from the command line
$ npm install
$ npm run build-production

Greetings Damien

**Comment by Prabhat2404** [comment]
@damienbod Thanks a lot, it works :+1:
