### ISSUE TITLE
switch to msbuild in master

### ISSUE THREAD

**Issue by damienbod** [damienbod/Angular2WebpackVisualStudio#64]
@robisim74 @FabianGosebrink 
Release is soon.
When do you think we should do this? now or at the release, project.json is dead.

msbuild is master, project.json in branch, keep for 6 months and kill.

**Comment by robisim74** [comment]
@damienbod I have not yet tried to open an existing .NET Core project in VS 2017: isn't it compatible? However, I think we should switch to new VS when it will be released (on March 7).

**Comment by damienbod** [comment]
Works good, and has support for Chrome debugging, haven't tried it yet, just read about it. node-sass has problems inside VS2017

**Comment by robisim74** [comment]
So what do you mean with _switch to msbuild in master_?

**Comment by damienbod** [comment]
We maintain 2 branches at the moment

master => VS2015 project.json version
VisualStudio2017 => VS2017 csproj version

At some stage I would merge the 2017 branch into the master, and create a new VS2015 branch which we will maintain for about 2 months, then project.jon is dead.

**Comment by robisim74** [comment]
Ok, I see. In my opinion, on March. @FabianGosebrink what do you think?

**Comment by FabianGosebrink** [comment]
Think most people are migrating to VS 2017 when it's released in March. My opinion: Damien's last proposal is cool, but let's merge the branches in March, then keep the old project.json branch for two months. I don't expect much webpack or Angular changes until then.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by damienbod** [comment]
@robisim74 @FabianGosebrink Time to switch, ok?

**Comment by FabianGosebrink** [comment]
Fine for me

**Comment by robisim74** [comment]
For me too

**Comment by damienbod** [comment]
done
