### ISSUE TITLE
Does not work with typescript 2.1.* and awesome-typescript-loader 3.*.*

### ISSUE THREAD

**Issue by kcsahoo** [damienbod/Angular2WebpackVisualStudio#66]
The solution does not work with typescript 2.1.* and awesome-typescript-loader 3.*.* for a large application that we have developed.
It works with the versions in your package.json file.
Can you help?

**Comment by kcsahoo** [comment]
I tried the sample app. with Typescript v 2.1.6 and awesome-typescript-loader  v3.0.4.
It does not work.
It gives the following error:
Uncaught reflect-metadata shim is required when using class decorators .... index.html:198

**Comment by robisim74** [comment]
Try to add the polyfill for _reflect-metadata_ in `angularApp > polyfills.ts` file:
`import 'reflect-metadata';`

**Comment by kcsahoo** [comment]
Tried it.
No success. Same error.

**Comment by damienbod** [comment]
This issue is related, seems like angular has problem with this
https://github.com/angular/angular/issues/13609

Greetings Damien

**Comment by kcsahoo** [comment]
Thanks.
will wait for resolution from angular team.
Your article and sample app is great.
It helped me to migrate from systemjs to webpack so smoothly.
Great work.
NB: Could not make aot work. Have you tried it?

**Comment by robisim74** [comment]
@damienbod I think it isn't an Angular problem, maybe an at-loader problem, but however a configuration problem. I explain: these two exports in `main.ts` file are not working:

```
export * from './polyfills';
export * from './vendor';
```

If I _remove them_, and _load polyfills & vendor directly_ in `webpack-dev.js` file, using the same configuration of production, the app works fine:

```
    entry: {
        'polyfills': './angularApp/polyfills.ts',
        'vendor': './angularApp/vendor.ts',
        'app': './angularApp/main.ts'
    },
```

```
        new webpack.optimize.CommonsChunkPlugin(
            {
                name: ['polyfills', 'vendor']
            }),
```

**Comment by kcsahoo** [comment]
Thanks a lot.
It works. You have saved my day.
I could not make aot (prod mode)  work even if I tried from command line.
Any idea where I could be going wrong?

**Comment by robisim74** [comment]
Are you using external libraries?

**Comment by kcsahoo** [comment]
I am just using your sample app to try that aot works.
I cannot succeed as it throws errors.

**Comment by FabianGosebrink** [comment]
Well can you post us some errors that we can reproduce it or see whats going on? Are you using any external libraries in addition to the ones already included?

**Comment by damienbod** [comment]
updated to template with the fix from @robisim74 
Everything works, both VS2015, VS2017, dev and aot, and also npm start

Massive thanks Roberto.

@kcsahoo 
Check out the latest version
Change to the csproj folder
$ npm install
$ dotnet restore
$ dotnet build
$ npm run build-production
$ dotnet run
Now you should be running using aot.

**Comment by damienbod** [comment]
@robisim74 @FabianGosebrink 
We have a build now for VS2017 and angular, it does a dotnet build npm dev build, npm production build

https://github.com/damienbod/Angular2WebpackVisualStudio/tree/VisualStudio2017

**Comment by kcsahoo** [comment]
I am using windows.
When I am trying to run step 
"node_modules\.bin\ngc"  -p ./tsconfig-aot.json
I am getting Duplicate Identifier 'propertyKey' in two files 
Any help?

**Comment by kcsahoo** [comment]
"node_modules\.bin\ngc" -p ./tsconfig-aot.json
slight correction
