### ISSUE TITLE
TS2307	Cannot find module '@angular/core'.	TypeScript Virtual Projects

### ISSUE THREAD

**Issue by nssidhu** [damienbod/Angular2WebpackVisualStudio#69]
I am Getting the following Error in the VS2015 Error List window, for the new module that i am trying to create. 

My project launches successfully though on port 8080, i have not completed my component yet, but was wondering why am i getting this error for new files that i created, but not for the existing files under the about & home modules ?

**Comment by damienbod** [comment]
Have you imported it in your module, compent?

**Comment by damienbod** [comment]
Can I close this?
