### ISSUE TITLE
Does it support ADFS Authentication

### ISSUE THREAD

**Issue by cvbc2010** [damienbod/Angular2WebpackVisualStudio#70]
i cannot find a best solution for implementing ADFS authentication, as .NET Core currently not supporting ADFS(if i am not wrong).

**Comment by damienbod** [comment]
As far as I know ADFS is not supported yet. maybe @PinpointTownes knows a solution for this?

Greetings Damien

**Comment by PinpointTownes** [comment]
It really depends on the exact ADFS version you're using, as they support different sets of authentication standards:

  - ADFS 2016 supports OpenID Connect, so it's natively supported by ASP.NET Core (that offers an OpenID Connect client middleware out-the-box).
  - ADFS 3.0/2012 supports OAuth2, so you can leverage the OAuth2 generic middleware that comes with ASP.NET Core to use it.
  - Older ADFS versions only support WS-Federation, which is currently not supported by .NET Core/ASP.NET Core.

**Comment by cvbc2010** [comment]
thanks for the info @damienbod @PinpointTownes , we are using ADFS 3.0 only. so can we use it directly as protecting WEB APIs with ADFS kind of.
