### ISSUE TITLE
Problems with new module

### ISSUE THREAD

**Issue by andyfurniss4** [damienbod/Angular2WebpackVisualStudio#71]
Sorry if these are simple questions - I'm new to Angular and Webpack.

I've added a new module called dynamics-search to a new fork of this repo.  I've followed the structure of the 'about' module and basically just renamed everything so far to try and create a new 'page' for my new module.

![file-structure](https://cloud.githubusercontent.com/assets/16683916/23366702/96309f78-fcff-11e6-904f-66d6b7a37657.PNG)

I've also added a route for this new module in app.routes.ts in the same way that the 'about' route is defined.

`export const routes: Routes = [
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: 'about', loadChildren: './about/about.module#AboutModule' },
    { path: 'dynamics-search', loadChildren: './dynamics-search/dynamics-search.module#DynamicsSearchModule', }
];`

Issues:

1. Visual Studio is telling me that the Angular module imports are broken with just a 'Cannot find module' error and red squigglies. However, I don't get an error when I build or run the application so is this just Visual Studio being weird?

2. When I run the app and click the new link that I've added to the navigation, it successfully loads the new module and the page displays as expected. However, if I think refresh the page, I get a 404. The same does not happen for the 'about' page - you get the 'Loading...' message and then the 'about' page is successfully displayed again. I feel like I've just missed something but not sure what.

Thanks

**Comment by andyfurniss4** [comment]
Also, is there a reason compileOnSave and buildOnSave are set to false in tsconfig?

**Comment by FabianGosebrink** [comment]
Hey @andyfurniss4 ,

> Also, is there a reason compileOnSave and buildOnSave are set to false in tsconfig?

Yes, we did not want to develop with automatic savings :) 

Concerning your problem: Have you tried to name the module without the dash?

BR

**Comment by andyfurniss4** [comment]
> Yes, we did not want to develop with automatic savings :)

OK, so it's a personal preference rather than for any specific reason? When do you compile your typescript if not on save/build?

> Concerning your problem: Have you tried to name the module without the dash?

I will give this a go and let you know. Currently having problems getting my typescript to compile after changing the names of everything.

**Comment by andyfurniss4** [comment]
> Have you tried to name the module without the dash?

Still no luck after removing the dash :( - It seems that navigating from the routerLink in the navigation works fine but from anywhere else it fails.

New route config:
`{ path: 'dynamicssearch', loadChildren: './dynamicssearch/dynamicssearch.module#DynamicsSearchModule' }`

And yeah, I figured it was a VS issue as everything seems to run OK. I'll consider using Code but I can live with it for now I think.

**Comment by robisim74** [comment]
See #56

**Comment by andyfurniss4** [comment]
Thanks @robisim74 - I had missed the new route from the Startup class.

Feel free to close.
