### ISSUE TITLE
HMR does not work when updating HTML 

### ISSUE THREAD

**Issue by artstalker** [damienbod/Angular2WebpackVisualStudio#73]
While testing HMR according to this article https://github.com/damienbod/Angular2WebpackVisualStudio/blob/master/HMR.md, I've found our that it works perfectly, but if I change anything in html files, webpage is not updated.
NPM console says that app has been rebuilt, browser console says that app is updated successfully, I see that HRM path file is added, but rendered page is not changed in the browser until you hit refresh.

Is it reproducible for everyone? What could be the problem?

**Comment by robisim74** [comment]
@artstalker I added a commit that should fix the problem.

@damienbod Without the following code:
```
if (module.hot) {
    module.hot.accept();
}
```
in the `main.t`s file, it's just a case that HMR was working. At the moment, I updated only the master branch, waiting for reports.

Greetings,

Roberto

**Comment by damienbod** [comment]
@artstalker thanks for reporting, @robisim74 thanks for the fix

**Comment by artstalker** [comment]
Thanks! That's exactly what I need!

**Comment by artstalker** [comment]
Sorry, where does this module.hot come from? I'm trying to apply the same approach for my own project, but it fails with 
` Cannot read property 'hot' of undefined`

**Comment by robisim74** [comment]
`let module: any;` in `main.ts` and `webpack-dev-server --hot --inline --port 8080` in `npm start`

**Comment by artstalker** [comment]
Yes, I declared exactly as you did in the commit above, but still module is undefined for me and it fails on this line of course:
`if (module.hot) {`

Do you know why? Who is setting the module variable? Maybe I'm missing some configuration?

**Comment by robisim74** [comment]
`webpack-dev-server` sets the module. Try to compare the version of the packages, and the webpack configuration. There are no other settings to be set using dev-server.

**Comment by artstalker** [comment]
I found out why it didn't work. Spent numerous amount of time on this...
So,  if you use any devtool except "source-map" (for example, eval-source-map, eval-cheap-module-source-map, eval-cheap-source-map etc), it just didn't work! module variable is always undefined no matter what.
I don't know what causes this issue, but I need to use some of eval-* devtools in order to boost building time in development mode. Haven't found any solution yet.

**Comment by artstalker** [comment]
Guys, I've found where the problem is.

You need to declare module as following:
`declare var module: any;`
Then it works with ALL devtools. Can you commit this? I just don't have time right now.

**Comment by robisim74** [comment]
Done. @artstalker Thanks for reporting.

Greetings,

Roberto
