### ISSUE TITLE
When switching order of chunks, app stops working

### ISSUE THREAD

**Issue by artstalker** [damienbod/Angular2WebpackVisualStudio#74]
Hi again :)

By default, the app has following order of the chunks: polyfills, app, vendor. That's because you do not overload chunksSortMode. So I've added additional attribute to HtmlWebpackPlugin:
` chunksSortMode: helpers.packageSort(['polyfills', 'vendor', 'app'])`
and the app stopped working
![angular webpack template - google chrome 2017-03-06 16 28 01](https://cloud.githubusercontent.com/assets/2846956/23613941/f710d0c6-0289-11e7-9469-0757ce434abe.png)

Do you know why it happens and how to fix that?

**Comment by artstalker** [comment]
I was able to fix this issue.
webpack.dev config has a bug in the configuration.
`new webpack.optimize.CommonsChunkPlugin({ name: ['app', 'polyfills'] })`
should be
`new webpack.optimize.CommonsChunkPlugin({ name: ['vendor', 'polyfills'] })`

**Comment by damienbod** [comment]
thanks, fixed in the VS2017 branches

**Comment by damienbod** [comment]
fixed. To use VS2015, you need to use the visual-studio-2015 branch, thanks for reporting
