### ISSUE TITLE
Start with Visual Studio 2017 and your project. It doesn't work.

### ISSUE THREAD

**Issue by j-nord** [damienbod/Angular2WebpackVisualStudio#76]
We have fresh install this project under visual-studio 2017.

npm: 4.1.2
node: 7.7.3

Task Runner: the command "yarn" was not found. Process terminated with code 1.

What's wrong?

**Comment by FabianGosebrink** [comment]
You have to install yarn globally either with chocolatey or run `npm install yarn -g`

**Comment by j-nord** [comment]
Thank's! It runs.
